### ISSUE TITLE
Can't deploy rivet init project

### ISSUE THREAD

**Issue by xeynyty** [rivet-gg/rivet#1713]
## Environment

- [x] Rivet Cloud
  - Game ID: https://hub.rivet.gg/projects/rivet-actors-8yd ???
- [ ] Rivet self-hosted local
  - Version/commit: [please provide]
- [ ] Rivet self-hosted cluster
  - Version/commit: [please provide]

## Steps to reproduce

1. rivet init
2. rivet deploy
3. profit!

## Workarounds

C:\Users\Administrator\WebstormProjects>rivet init
> What is your project name? rivet-actors
> What language will you write your Rivet Actor in? TypeScript
> What config format do you prefer? JSON (rivet.json)
> Would you like to log in to Rivet now? Yes
> Are you using Rivet Cloud? Yes

Creating new Rivet project at C:\Users\Administrator\WebstormProjects\rivet-actors
Project created successfully.

Login in to Rivet...
Waiting for browser...

If browser did not open, open this URL to login:
************** // hide this
Logged in

    ==========   Welcome to Rivet!   ==========

Resources:

  Documentation:      https://rivet.gg/docs
  Discord:            https://rivet.gg/discord
  Issues:             https://github.com/rivet-gg/rivet/issues
  Questions & Ideas:  https://github.com/orgs/rivet-gg/discussions
  Configure IDE:      https://docs.deno.com/runtime/getting_started/setup_your_environment

Next steps:

  $ cd rivet-actors
  $ rivet deploy

C:\Users\Administrator\WebstormProjects>cd rivet-actors

C:\Users\Administrator\WebstormProjects\rivet-actors>rivet deploy
> Environment Staging (staging)
[Building] name=manager owner=rivet

Command failed with status: exit code: 1
stderr:
X [ERROR] Could not resolve "\\Users\\Administrator\\AppData\\Roaming\\rivet\\actor-sdk\\a5f4a47d6ca38a55c17a4feb615318c54f109cc09b4e1157cf52c21c41e62d32\\manager\\src\\mod.ts" [plugin deno-resolver]

  The plugin "ar" didn't set a resolve directory, so esbuild did not search for "\\Users\\Administrator\\AppData\\Roaming\\rivet\\actor-sdk\\a5f4a47d6ca38a55c17a4feb615318c54f109cc09b4e1157cf52c21c41e62d32\\manager\\src\\mod.ts" on the file system.

[UNCAUGHT] Error: Build failed with 1 error:
error: Could not resolve "\\Users\\Administrator\\AppData\\Roaming\\rivet\\actor-sdk\\a5f4a47d6ca38a55c17a4feb615318c54f109cc09b4e1157cf52c21c41e62d32\\manager\\src\\mod.ts"
  at failureErrorWithLog (file:///C:/Users/Administrator/AppData/Roaming/rivet/js-utils/bbb1352ed18f45215d4f00dacc4c4351fb80473181d00404c8f5626e11201f98/node_modules/.deno/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1651:15)
  at file:///C:/Users/Administrator/AppData/Roaming/rivet/js-utils/bbb1352ed18f45215d4f00dacc4c4351fb80473181d00404c8f5626e11201f98/node_modules/.deno/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1059:25
  at runOnEndCallbacks (file:///C:/Users/Administrator/AppData/Roaming/rivet/js-utils/bbb1352ed18f45215d4f00dacc4c4351fb80473181d00404c8f5626e11201f98/node_modules/.deno/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1486:45)
  at buildResponseToResult (file:///C:/Users/Administrator/AppData/Roaming/rivet/js-utils/bbb1352ed18f45215d4f00dacc4c4351fb80473181d00404c8f5626e11201f98/node_modules/.deno/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1057:7)
  at file:///C:/Users/Administrator/AppData/Roaming/rivet/js-utils/bbb1352ed18f45215d4f00dacc4c4351fb80473181d00404c8f5626e11201f98/node_modules/.deno/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1086:16
  at responseCallbacks.<computed> (file:///C:/Users/Administrator/AppData/Roaming/rivet/js-utils/bbb1352ed18f45215d4f00dacc4c4351fb80473181d00404c8f5626e11201f98/node_modules/.deno/esbuild@0.20.2/node_modules/esbuild/lib/main.js:704:9)
  at handleIncomingPacket (file:///C:/Users/Administrator/AppData/Roaming/rivet/js-utils/bbb1352ed18f45215d4f00dacc4c4351fb80473181d00404c8f5626e11201f98/node_modules/.deno/esbuild@0.20.2/node_modules/esbuild/lib/main.js:764:9)
  at Readable.readFromStdout (file:///C:/Users/Administrator/AppData/Roaming/rivet/js-utils/bbb1352ed18f45215d4f00dacc4c4351fb80473181d00404c8f5626e11201f98/node_modules/.deno/esbuild@0.20.2/node_modules/esbuild/lib/main.js:680:7)
  at Readable.emit (ext:deno_node/_events.mjs:393:28)
  at addChunk (ext:deno_node/_stream.mjs:2438:16)

## More information

Windows 11, rust and deno was installed before

**Comment by NathanFlurry** [comment]
@xeynyty Welcome! This looks like a Windows-specific error on our end. I'll check this out.

In the meantime, this should work without issue in WSL.

**Comment by NathanFlurry** [comment]
@xeynyty 24.6.1 has the fix for Windows. Run the installer again and give it a go – https://github.com/rivet-gg/rivet?tab=readme-ov-file#install-cli
